### ISSUE TITLE
Is Lambda effectively dead?

### ISSUE THREAD

**Issue by LordAthens** [ZeroQI/Lambda.bundle#41]
I have tried every which way from Sunday to get Lambda working without success.  All I needed was a way to get the nfo file created from DVR'd (via Plex) shows.  From what I've read, the new Plex Scanner (even when switching back to the legacy scanner).

I just want to confirm that Lambda is dead before I invest any more time in to trying to make it work.

**Comment by ZeroQI** [comment]
New type libraries to not support agents.
Try creating a new library with tvdb agent and not new plex one. You haven't specified the metadata agent used while it is primordial since this is a secondary agent and need to be included on this line

https://github.com/ZeroQI/Lambda.bundle/blob/master/Contents/Code/__init__.py#L702
